// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ca8eeb1d-2c81-4df3-b694-286edf795cd6",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_bfw2gSMMr",
    "aws_user_pools_web_client_id": "31terv319f74rnk2qafib4ln9b",
    "oauth": {}
};


export default awsmobile;
